# Ch3: Creating Tensors

In [50]:
import torch
import numpy as np
print(torch.__version__)

2.6.0+cu124


## Create Tensors
We can create tensors from existing data structures, such as:
- lists
- tuples
- NumPy arrays

In [51]:
tensor_from_list=torch.tensor([1,2,3,4,5])
tensor_from_list

tensor([1, 2, 3, 4, 5])

In [52]:
tensor_from_tuple=torch.tensor((6,7,8,9,10))
tensor_from_tuple

tensor([ 6,  7,  8,  9, 10])

In [53]:
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
tensor_from_array

tensor([11, 12, 13, 14, 15])

We can also have `torch` create tensors with initial values. In this case, we specify the dimensions of the tensor.

In [54]:
tensor_empty = torch.empty(3,4)
tensor_empty

tensor([[5.9728e+03, 4.5856e-41, 5.9728e+03, 4.5856e-41],
        [5.9727e+03, 4.5856e-41, 5.9727e+03, 4.5856e-41],
        [5.9727e+03, 4.5856e-41, 5.9727e+03, 4.5856e-41]])

In [55]:
tensor_zeros = torch.zeros(3,4)
tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
tensor_ones= torch.ones(3,4)
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Random values is also possible.

In [57]:
# random numbers, uniform distr
tensor_rand_un = torch.rand(4,5)
tensor_rand_un

tensor([[2.1382e-02, 3.6643e-01, 2.0535e-01, 1.9226e-01, 3.5434e-01],
        [2.1795e-01, 1.0574e-04, 1.4056e-01, 6.0028e-01, 5.6578e-01],
        [9.4895e-02, 9.6953e-02, 3.7144e-01, 2.6844e-02, 1.9478e-01],
        [7.8418e-01, 5.8637e-01, 1.7138e-01, 1.0558e-01, 8.1767e-01]])

In [58]:
# random numbers, normal distr
tensor_rand_norm = torch.randn(4,5)
tensor_rand_norm

tensor([[-0.1851, -0.4297,  0.1519, -0.1700,  0.9553],
        [ 1.0025,  1.0673,  0.2567,  0.2639,  0.4833],
        [-1.5303,  0.4898, -1.6568,  2.4467, -0.9278],
        [ 0.7583, -0.4860,  1.0937,  1.0298,  0.2926]])

In [59]:
# random ints, uniform distr
tensor_rand_int = torch.randint(5,10,(4,5))
tensor_rand_int

tensor([[8, 5, 5, 9, 9],
        [6, 5, 8, 6, 9],
        [5, 6, 8, 7, 5],
        [8, 9, 6, 6, 8]])

Finally, we can pass in a tensor as the parameter if we want to have the same data type, device, and dimension as the parameter.

In [60]:
tensor_ones = torch.ones_like(tensor_rand_int)
tensor_ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

## Tensor Attributes
It's important to know the attributes of a tensor, such as:
- device location
- data type
- dimensions
- rank

In [61]:
first_tensor = torch.tensor([1,2,3,4,5,6])
print('device:', first_tensor.device)
print('dtype:', first_tensor.dtype)
print('dimensions:', first_tensor.shape)
print('rank:', first_tensor.ndim)

device: cpu
dtype: torch.int64
dimensions: torch.Size([6])
rank: 1


In [62]:
second_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print('device:', second_tensor.device)
print('dtype:', second_tensor.dtype)
print('dimensions:', second_tensor.shape)
print('rank:', second_tensor.ndim)

device: cpu
dtype: torch.int64
dimensions: torch.Size([3, 3])
rank: 2


## Tensor Data Types
When creating a tensor, we can explicitly set the data type with the `dtype` parameter.

In [63]:
int_tensor= torch.tensor([1,2,3,4,5],dtype=torch.int8)
float_tensor= torch.tensor([6,7,8,9,10], dtype=torch.float32)
short_tensor= torch.tensor([6,7,8,9,10], dtype=torch.int16)

We can also cast tensors between compatible data types.

In [64]:
# method 1: tensor.dtype()
print('before:', int_tensor.dtype)
int_tensor = int_tensor.float()
print('after:', int_tensor.dtype)

before: torch.int8
after: torch.float32


In [65]:
# method 2: tensor.to(dtype=)
print('before:', short_tensor.dtype)
last_tensor = short_tensor.to(dtype=torch.int8)
print('after:', last_tensor.dtype)

before: torch.int16
after: torch.int8


When working with different data types, PyTorch will automatically cast types to the larger data type.

## Random Samples
- `torch.rand()` gets random values from uniform distribution [0,1]
- `torch.randn()` gets random values from standard normal distribution (mean 0, std 1)
- `torch.randint()` gets random ints generated uniformly between specified low and high values

Note that we use `torch.manual_seed()` for seeding the randomness. We have to put it at the top of every cell in order to make each run consistent.

In [66]:
torch.manual_seed(17)

rand = torch.rand(3)
rand

tensor([0.4342, 0.5351, 0.8302])

In [67]:
torch.manual_seed(17)

randn = torch.randn(3,3)
randn

tensor([[-1.4135,  0.2336,  0.0340],
        [ 0.3499, -0.0145, -0.6124],
        [-1.1835, -1.4831,  1.8004]])

In [68]:
torch.manual_seed(17)

randint = torch.randint(1,10,(3,3,3))
randint

tensor([[[7, 7, 3],
         [5, 9, 8],
         [1, 8, 4]],

        [[7, 9, 2],
         [6, 9, 1],
         [3, 3, 6]],

        [[2, 7, 1],
         [8, 9, 1],
         [6, 7, 5]]])

We can still specify parameters like `dtype` or `device` when creating with random sampling.

## Tensors Like Other Tensors
We can create tensors that share similar properties to another one. PyTorch functions will reuse the same name as other methods we've learned, but with the `_like` suffix (ex: `torch.rand_like()`).

In [69]:
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [70]:
torch.manual_seed(17)
rand_tensor=torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.4342, 0.5351, 0.8302, 0.1239, 0.0293],
        [0.5494, 0.3825, 0.5463, 0.4683, 0.0172]])

In [71]:
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [72]:
torch.full_like(starting_tensor,7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])